apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: klabater
  source:
    path: kubernetes/apps/nginx
    repoURL: git@github.com:koyaaniskassie/klabater.git
    targetRevision: HEAD
    helm:
      releaseName: nginx
      valueFiles:
        - values.yaml
